### PR TITLE
2024.16 translation

### PR DESCRIPTION
**Pull request by nOester**
Hi @eleu , hi @vladyslav-tk 
Please find here the translations.

### CODE REVIEW

**Comment by eleu** [comment]
@nOester maybe one of the translations is missing? 
image

**Comment by nOester** [comment]
> @nOester maybe one of the translations is missing?

@eleu : Hm, yes you are right. But the key is not in the locales. I'm going to integrate it and update the PR.

**Review by vladyslav-tk — APPROVED** [review]

**Comment by vladyslav-tk** [comment]
@nOester I fixed the translation for "Tools", please check if it is correct

**Comment by vladyslav-tk** [comment]
@nOester I will merge this PR, we can create a new one to change translation if needed

**Pull request merged**
